
services:             # aqui começa a lista de containers que serão criados

  backend:            # nome que demos a esse serviço (pode ser qualquer nome)
    build: .          # diz pro Compose construir a imagem usando o Dockerfile da pasta atual
    ports:
      - "5000:5000"   # mapeia a porta 5000 do container para a porta 5000 do seu PC
                      # formato: "porta-do-seu-pc:porta-do-container"
    env_file:
      - .env  # define a variável de ambiente DATABASE_URL dentro do container, usando o valor do arquivo .env
    depends_on:
      db:        # diz que o serviço "backend" depende do serviço "db" (PostgreSQL)
        condition: service_healthy       # O backend só sobe quando o banco passar no healthcheck      
    volumes:
      - ./:/app  #  monta a pasta atual do seu PC (.) dentro do container em /app — o mesmo lugar onde o código está. Qualquer mudança que você salvar no VS Code aparece instantaneamente dentro do container
  

  db:                 # nome do serviço para o banco de dados
    image: postgres:15  # usa a imagem oficial do PostgreSQL versão 15
    env_file:
      - .env  #passa todas as variáveis do .env pro container do banco
      
    volumes:
      - dados_db:/var/lib/postgresql/data  # monta um volume para persistir os dados do banco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]  # verifica se o banco está pronto para receber conexões
      interval: 5s  #define o intervalo entre cada verificação
      retries: 5  #define o número de tentativas antes de considerar o serviço como "não saudável"
## --- CMD-SHELL = permite usar variáveis de ambiente do container 
## --- $$POSTGRES_USER = referencia a variável POSTGRES_USER definida no .env (o $$ evita que o Compose interprete antes de passar pro container)
       
  nginx:              # nome do serviço para o NGINX
    image: nginx:latest  # usa a imagem oficial do NGINX
    ports:
      - "8888:80"          # mapeia a porta 80 do container para a porta 80 do seu PC
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   # monta o arquivo de configuração do NGINX// Substitui as config padrão do nginx pela minha
      - ./frontend:/usr/share/nginx/html           # monta a pasta do frontend como somente leitura // Coloca os meus arq. HTML dentro do container onde o NGINX serve
    depends_on:
      - backend          # diz que o serviço "nginx" depende do serviço "backend" (Flask), só sobe depois que o Flask estiver rodando
    restart: on-failure   # reinicia o container caso ele pare de funcionar

volumes:             # aqui definimos os volumes que serão usados pelos serviços
  dados_db:            # nome do volume para o banco de dados