events{}


http{
    resolver 127.0.0.11 valid=30s;  #configura o NGINX para usar o DNS interno do Docker para resolver
                                    # os nomes dos serviços (como "backend"), garantindo que ele possa encontrar
                                    # o container do Flask mesmo que o IP mude.
    
    server {
        listen 80; #O ngix escuta a porta 80 para receber as requisições HTTP

        location / {    #tudo que acessar a raiz do site vai buscar arquivos estáticos (HTML/CSS/JS)
            root /usr/share/nginx/html;     #pasta dentro do container onde ficam os arquivos do frontend
            index index.html;
        }

        location /api/ {    #qualquer rota que começar com /api/ vai ser redirecionada pro Flask
            set $backend "http://backend:5000";     # Criando uma variável que guarda o endereço do backend (Flask)
                                                    # ao usar uma variável em vez do nome direto, o NGINX passa a resolver
                                                    # o endereço só quando chega uma requisição, não na inicialização
            proxy_pass $backend$request_uri;   #endereço interno do container Flask + o caminho da requisição original (/api/tarefas)
            proxy_set_header Host $host;    #mantém o endereço original do usuário no cabeçalho da requisição
        }
    }
}